# Generated by Django 3.0.2 on 2020-02-02 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_magnificent_messages', '0003_auto_20200118_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
