# Generated by Django 2.2.4 on 2019-11-21 13:38

from django.db import migrations, models
import django_magnificent_messages.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFieldTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', django_magnificent_messages.fields.JSONField()),
            ],
        ),
    ]
