# Generated by Django 2.2.4 on 2019-11-21 18:51

from django.db import migrations
import django_magnificent_messages.fields
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfieldcustommodel',
            name='field',
            field=django_magnificent_messages.fields.JSONField(decode=tests.models.custom_decode, encode=tests.models.custom_encode),
        ),
    ]
